# Generated by Django 5.0.3 on 2024-04-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilemodel_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='bio',
        ),
    ]
